name: GitHub Flow APK Builder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Set up JDK 17 Environment
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant Execute Permission for Gradle Launcher
      run: chmod +x gradlew

    - name: Compile and Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload Finished APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Strec-Application-Package
        path: app/build/outputs/apk/debug/app-debug.apk

